name: TDS Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 21f3002912@ds.study.iitm.ac.in
        run: echo "Hello World"

      - name: Complete
        run: echo "Done"
